## Objective

At the end of the experiment you will be able to 

* execute linear algebraic functions
* explain difference between numpy arrays and  Python lists

### Introduction to Numpy

NumPy (Numerical Python) is a Python library for scientific computing, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), the performance is very good.

It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.


**How are NumPy arrays different from Python lists?**

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


Now it is time to work on practicals. Following Are the given Exercise:


#### Exercise 1: Import the numpy package under the name np

In [0]:
import numpy as np

#### Exercise 2: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [3]:
X = np.array([1, 45, 60, 90])
print("sine: {} \ncosine: {} \ntangent: {}".format(np.sin(X),np.cos(X),np.tan(X)))

sine: [ 0.84147098  0.85090352 -0.30481062  0.89399666] 
cosine: [ 0.54030231  0.52532199 -0.95241298 -0.44807362] 
tangent: [ 1.55740772  1.61977519  0.32004039 -1.99520041]


#### Exercise 3: Given an array *X*. Convert angles from radians to degrees.

X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [6]:
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
deg = np.degrees(X)
print(deg)

[-180.  -90.   90.  180.]


#### Exercise 4: Given an arrya *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [7]:
X = np.array([-180.,  -90.,   90.,  180.])
np.deg2rad(X)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

#### Exercise 5: Given an array *X*. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of *X*, element-wise. 

X = np.array([-1., 0, 1.])

In [8]:
X = np.array([-1., 0, 1.])
print(np.sinh(X))
print(np.cosh(X))
print(np.tanh(X))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


#### Exercise 6: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [0]:
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [12]:
np.round(X), np.ceil(X), np.floor(X)

(array([  4.,   2.,  44.,  26.,  -1., -10.,  -7.]),
 array([ 5.,  3., 45., 26., -1., -9., -6.]),
 array([  4.,   2.,  44.,  25.,  -2., -10.,  -7.]))

#### Exercise 7: Given an array *X*. Calculate the difference between neighboring elements, element-wise.

X = np.array([11, 13, 23, 45, 77])

In [13]:
X = np.array([11, 13, 23, 45, 77])
np.diff(X)

array([ 2, 10, 22, 32])

#### Exercise 8: Given two arrays *X* and *Y*. Find the cross product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [0]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

In [19]:
np.cross(X, Y)

array([-3,  6, -3])

#### Exercise 9: Given two arrays *X* and *Y*. Find the dot product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [20]:
np.dot(X, Y)

32

#### Exercise 10: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [21]:
np.divide(X, Y)

array([0.25, 0.4 , 0.5 ])

In [22]:
np.true_divide(X, Y)

array([0.25, 0.4 , 0.5 ])

In [23]:
np.floor_divide(X, Y)

array([0, 0, 0])

#### Exercise 11: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [24]:
np.power(X, Y), X ** Y

(array([  1,  32, 729]), array([  1,  32, 729]))

#### Exercise 12: Given one array *X* and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.


X = np.array([1, 2, 3])

In [0]:
X = np.array([1, 2, 3])

In [0]:
Y = 3

In [30]:
np.remainder(X, Y), np.fmod(X, Y)

(array([1, 2, 0]), array([1, 2, 0]))

#### Exercise 13:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [8]:
import numpy as np
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
y = X.copy()
id(X), id(y)

(140419803304784, 140419271195024)

#### Exercise 14: Given an array *X*. Compute the square of *X*, element-wise.

X = np.array([2, 3, 4, 5, 6])

In [31]:
X = np.array([2, 3, 4, 5, 6])
np.square(X)

array([ 4,  9, 16, 25, 36])

#### Exercise 15: Given an array *X*. Compute the absolute value of *X*.

X = np.array([[-44, 3], [4, -3]])

In [0]:
X = np.array([[-44, 3], [4, -3]])

In [33]:
np.abs(X)

array([[44,  3],
       [ 4,  3]])

#### Exercise 16: Given an array *X*. Compute an element-wise indication of the sign of *X*, element-wise.

X = np.array([1, 3, 0, -1, -3])

In [34]:
X = np.array([1, 3, 0, -1, -3])
print(np.sign(X))

[ 1  1  0 -1 -1]


#### Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [35]:
np.random.rand(2)

array([0.96092018, 0.27592605])

#### Exercise 18: Given an array *gaussian*. How do you get the number of dimensions of the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [37]:
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.ndim

3

#### Exercise 19: Given an array *gaussian*. How do you get the shape of an array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [38]:
gaussian.shape

(2, 3, 4)

#### Exercise 20: Given an array *gaussian*. How do you get the total number of elements in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [39]:
gaussian.size

24

#### Exercise 21: Given an array *gaussian*. How do you get memory consumed by each item in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [40]:
gaussian.itemsize

8

#### Exercise 22: Given an array *twenty*. How do you access first two rows and three columns

twenty = (np.arange(4 * 5)).reshape(4, 5)

In [10]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

#### Exercise 23: Given an array *twenty*. How do you reverse the order of elements along columns?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [13]:
twenty[::-1]


array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

#### Exercise 24: Given an array *twenty*. How do you reverse the order of elements along rows?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [43]:
twenty[..., ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

#### Exercise 25: Given an array *twenty*. How do you shuffle the array along axis - 0


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [0]:
np.random.shuffle(twenty)

In [46]:
twenty

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])