## Objective

At the end of this experiment you will be able to

* create arrays, vectors and matrices using Numpy
* perform operations on vectors and matrices

### Introduction to Numpy

NumPy (Numerical Python) is a Python library for scientific computing, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), the performance is very good.

It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.


**How are NumPy arrays different from Python lists?**

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


Now it is time to work on practicals. Following Are the given Exercise:


#### Exercise 1: Import the numpy package under the name np

In [0]:
import numpy as np

#### Exercise 2: Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise 3: Create an array of 20 ones

In [3]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Exercise 4: Create an array of 10 fours

In [4]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

#### Exercise 5: Create an array of integers from 20 to 60

In [6]:
np.arange(20, 61)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

#### Exercise 6: Create an array of even integers from 20 to 60

In [7]:
np.arange(20, 61, 2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60])

#### Exercise 7: Create a 4 * 4 indenty matrix

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Exercise 8: Create a 3 * 3 matrix with values range from 0 to 8

In [11]:
np.arange(0,9).reshape([3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Exercise 9: Generate a random number between 0 and 1 using numpy

In [12]:
np.random.rand(1)

array([0.14224467])

#### Exercise 10: Generate an array of 15 random numbers sampled from a standard normal distribution

In [13]:
np.random.randn(15)

array([ 1.77662907,  0.31999817, -0.25703812,  0.12943414, -0.22592734,
        0.02303229, -0.09622939,  1.20723147, -0.91849145, -0.90336969,
        1.90743656,  0.01735587,  0.09938163,  0.62805548, -0.34721536])

#### Exercise 11: Create a vector with values ranging from 10 to 49 

In [14]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Exercise 12: Create a numpy array from a List

In [15]:
numberslist = [[1, 2], [3, 4]]
numbersarray = np.array(numberslist)
print(numbersarray)

[[1 2]
 [3 4]]


#### Exercise 13: Find indices of non-zero elements from [122,233,0,0,44,3]

In [16]:
nz = np.nonzero([122,233,0,0,44,3])
print(nz)

(array([0, 1, 4, 5]),)


#### Exercise 14:  Create a 3 * 3 * 3 array with random values

In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.13241635 0.28659505 0.64691013]
  [0.91386584 0.72542577 0.84235742]
  [0.30074339 0.0828797  0.24972133]]

 [[0.1953195  0.484598   0.46970615]
  [0.44663772 0.54653643 0.3807677 ]
  [0.38769832 0.45742808 0.52844014]]

 [[0.51244631 0.44694123 0.08393378]
  [0.38559679 0.19339379 0.91553434]
  [0.57948016 0.74245293 0.98757791]]]


#### Exercise 15: Create a 10 * 10 array with random values and find the minimum and maximum values

In [18]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.014106835482129987 0.9956416970937092


#### Exercise 16: Create a random vector of size 10 and find the mean value

In [19]:
Z = np.random.random(10)
m = Z.mean()
print(m)

0.5999357466429868


#### Exercise 17:  Create a checkerboard 8 * 8 matrix using the tile function 

In [20]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Exercise 18: Given two arrays *A* and *B*, perform the below operations.

* A + B
* A - B
* A * B
* A / B
* A ** 3

A = np.arange(1,6)

B = np.arange(6,15, 2)

In [0]:
A = np.arange(1,6)
B = np.arange(6,15, 2)

In [22]:
A + B

array([ 7, 10, 13, 16, 19])

In [23]:
A - B

array([-5, -6, -7, -8, -9])

In [24]:
A * B

array([ 6, 16, 30, 48, 70])

In [25]:
A / B

array([0.16666667, 0.25      , 0.3       , 0.33333333, 0.35714286])

In [26]:
A ** 3

array([  1,   8,  27,  64, 125])

#### Exercise 19: Given an Array *A*. Calculate the square root of elements in it.

A = np.arange(1,20, 2)

In [0]:
A = np.arange(1,20, 2)

In [28]:
A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.sqrt(A)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

#### Exercise 20: Given an array *A*. Calculate the exponential of elements in it.

A = np.arange(1, 20, 2)

In [31]:
A = np.arange(1, 20, 2)
np.exp(A)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])