# IoT & Smart Analytics
## A Program by IIIT-H and TalentSprint

## Learning Objectives
At the end of the experiment, participants will be able to : 
* understand & implement Perceptron  


In [ ]:
import pandas as pd
import numpy as np
from pprint import pprint
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

#### Loading data

In [ ]:
!wget  https://cdn.extras.talentsprint.com/IOT/Data/iris.csv

--2022-04-02 10:00:21--  https://cdn.extras.talentsprint.com/IOT/Data/iris.csv
Resolving cdn.extras.talentsprint.com (cdn.extras.talentsprint.com)... 172.105.52.210
Connecting to cdn.extras.talentsprint.com (cdn.extras.talentsprint.com)|172.105.52.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4610 (4.5K) [application/octet-stream]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   4.50K  --.-KB/s    in 0s      

2022-04-02 10:00:24 (399 MB/s) - ‘iris.csv’ saved [4610/4610]



In [ ]:
df = pd.read_csv("/content/iris.csv")
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
df = df[df['Name'] != 'Iris-virginica']
df['Name'].replace(to_replace = ['Iris-setosa', 'Iris-versicolor'], value = [1, 0], inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  100 non-null    float64
 1   SepalWidth   100 non-null    float64
 2   PetalLength  100 non-null    float64
 3   PetalWidth   100 non-null    float64
 4   Name         100 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 8.8 KB


In [ ]:
df.loc[[5, 60, 90]]  #select few samples to see the DataFrame

SepalLength  SepalWidth  PetalLength  PetalWidth  Name
5           5.4         3.9          1.7         0.4     1
60          5.0         2.0          3.5         1.0     0
90          5.5         2.6          4.4         1.2     0

### Single Layer Perceptron

A node, also called a neuron or Perceptron, is a computational unit that has one or more weighted input connections. Use a transfer function that combines the inputs and gives the output connection. Nodes are then organized into layers to comprise a network.

Let us see how the output is measured at each neuron

![alt text](https://cdn.extras.talentsprint.com/IOT/Images/Perceptron.png)

### Part-A: Understand Perceptron using mathematical approach

#### Performing for only one sample

In [ ]:
# Let us take 5th sample as input x1, x2, x3, x4
one_neuron_inputs  = np.array([5.4, 3.9,  1.7,  0.4]) 
weights =  np.array([0.7, 0.6, -1.0, -1.0]) # You can give the random weights w1, w2, w3, w4

In [ ]:
W=weights[:,np.newaxis]
print(' weights :\n',W)
print('shape: ',W.shape)
X=one_neuron_inputs[:,np.newaxis]
print('input neurons :\n',X)
print('shape: ',X.shape)

 weights :
 [[ 0.7]
 [ 0.6]
 [-1. ]
 [-1. ]]
shape:  (4, 1)
input neurons :
 [[5.4]
 [3.9]
 [1.7]
 [0.4]]
shape:  (4, 1)


In [ ]:
W.T.dot(X)
## OR np.dot(W.T,X)

array([[4.02]])

#### Defining function that returns the sum of product of inputs and weights

In [ ]:
def weighted_sum(inputs, weights):
    total = weights.T.dot(inputs)
    return total

In [ ]:
weighted_sum(W,X)

array([[4.02]])

**Step Function**


A Step Function is one of the most common activation function in neural networks. The function produces binary output.

The output is a certain value, $A_1$, if the input sum is above a certain threshold and $A_0$ if the input sum is below a certain threshold. The values used by the Perceptron were $A_1$ = 1 and $A_0$ = 0.

![alt text](https://cdn.talentsprint.com/aiml/Experiment_related_data/step_function.png)

These kinds of step activation functions are useful for binary classification schemes. In other words, when we want to classify an input pattern into one of two groups, we can use a binary classifier with a step activation function.

#### Defining step function

In [ ]:
def Step_Fun(number):
    if number >= 2: # Threshold value is 2
        return 1
    else:
        return 0

In [ ]:
Step_Fun(W.T.dot(X))

1

In [ ]:
weighted_sum(W,X)

array([[4.02]])

#### Performing for all samples

Performing weigthed sum  and Step function for each of the feature by taking random weights and finding accuracy for actuals and predictions. 

In [ ]:
df.values[:,:-1].T

In [ ]:
Xn=df.values[:,:-1].T
print(Xn.shape)
y=df.values[:,-1]
print(W.shape)

(4, 100)
(4, 1)


In [ ]:
r=weighted_sum(W,Xn)
r

#### Defining step function to adapt numpy arrray

* np.where(cond , value_if cond is true , value if cond is false )

In [ ]:
def Step_Fun(Ap):
    r=np.where(Ap>=2,1,0) #threshold =2
    return r

In [ ]:
y_pred=Step_Fun(weighted_sum(W,Xn))
y_pred

#### Calculating Accuracy

In [ ]:
acc = accuracy_score(y, y_pred)
print("Accuracy of the Perceptron using mathematical approach", acc)

Accuracy of the Perceptron using mathematical approach 1.0


### Part- B: Perceptron from Sklearn

1. From the given data, Select features and labels
2. Split the data into train and test sets 
3. Train using perceptron Classifier

In [ ]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth  Name
0          5.1         3.5          1.4         0.2     1
1          4.9         3.0          1.4         0.2     1
2          4.7         3.2          1.3         0.2     1
3          4.6         3.1          1.5         0.2     1
4          5.0         3.6          1.4         0.2     1

In [ ]:
labels = df['Name']
features = df.drop('Name', axis = 1)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(features, labels, test_size = 0.2)

In [ ]:
from sklearn.linear_model import Perceptron
model = Perceptron() 
# Fitting the data into the model
model.fit(xtrain, ytrain)
# Predicting the labels for test data
accuracy = model.score(xtest, ytest)
print("Accuracy of the Perceptron using sklearn", accuracy)

Accuracy of the Perceptron using sklearn 1.0
